#Arithmetic operations
num1=int(input("Enter first number:"))
num2=int(input("Enter second number:"))
print("the sum : ",num1+num2)
print("the multiplication : ",num1*num2)
print("the power : ",num1**num2)
print("the subtraction : ",num1-num2)
print("the division : ",num1/num2)
print("the division : ",num1//num2)
print("the division : ",num1%num2)
